### ISSUE TITLE
Is there any randomness in the clustering results?

### ISSUE THREAD

**Issue by Classmate-Huang** [ssarfraz/FINCH-Clustering#22]
Hi, I fixed the random seed and input data and then applied FINCH for clustering. But I found that the results obtained by each clustering are different, what should I do to ensure that I can get a fixed result every time?

![image](https://user-images.githubusercontent.com/59324642/150946085-f60caafd-9633-4a50-bb46-e4694b5949e7.png)

P.S. I have a large amount of data (hundreds of thousands) and use the NNDescent method in 'pynndescent', is it possible that this is the cause？ What can I do? 

Looking forward to your reply, thank you very much

**Comment by ssarfraz** [comment]
Yes thats because of the use of ANN method (pynndescent in this case).  Though it should not have much impact on the cluster purity in the end, but to have consistent runs every time, I suppose there should be a way to fix the random seed. If I look at pynndescent implementation it seems it takes a 'random_state' parameter: https://pynndescent.readthedocs.io/en/latest/api.html#pynndescent . You may try it.  If it is well implemented, then this should fix the issue
