### ISSUE TITLE
Different Clustering results when using python and matlab implementation

### ISSUE THREAD

**Issue by Cornibouchon** [ssarfraz/FINCH-Clustering#24]
I realized, that the python implementation does yield different results than the matlab version.

This I have found out by first comparing a python evaluation of the tw-finch clustering results against the provided matlab evaluation one, with one of the provided datasets and the features from the TW-FINCH paper.
After looking a little more into the issue, I have found that already in the first steps of the clustering process, both version assign the same features/frames to different clusters and the number of clusters is drastically different too, which explains the performance differences.

Have you encountered this issue and if yes are there solutions?

**Comment by Cornibouchon** [comment]
Dear Dr. Safraz

First of all, thank you for your great work.
Since I would like to extend your algorithm (part of an academic work) it would be helpful if you can get in touch we me to resolve this issue.


Please find attached the code to produce the following plots. I have also attached the extracted results from the matlab script "run_on_dataset.m". I only added the output of TW-FINCH containing the # of clusters at each step.

Please find below the code to:
1) Apply the TW-FINCH clustering to the 50Salads Dateset (Same structure as provided within the original paper) and extract the same metrics.
2) The pre-computed output from the matlab evaluation script as well as from the python implementation
3) The Script to generate the Graph



![50S_cluster_delta_python_vs_matlab_orig_HoF_IdT](https://user-images.githubusercontent.com/23170195/187476364-c60d53dd-cd5a-4c03-ad3c-0849002b629c.png)


[reproduce_clust_delta.zip](https://github.com/ssarfraz/FINCH-Clustering/files/9454172/reproduce_clust_delta.zip)

**Comment by ssarfraz** [comment]
The issue was actually quite subtle (1). float64 dtype causing numpy to have some precision errors in the distance mat multiplication in TW-FINCH, in turn this was fixed by casting data properly to float32. (2.) the time_stamp were starting from 0 which needed to start from 1 instead. I have pushed the changes along with the python video reading and evaluation scripts I have prepared based on your provided scripts. Because of  this though you might still see some intermediate clustering differences but overall it provides similar results as matlab.
