### ISSUE TITLE
TWFinch code missing YTI without 75% background option; unable to reproduce accuracy

### ISSUE THREAD

**Issue by April-lyl** [ssarfraz/FINCH-Clustering#28]
For YTI dataset, I have read CTE, but I can't reproduce the code to remove background frames. The replicated f1 is much lower, and the 
mof is close.
I would appreciate any guidance on how to do this in YTI dataset. Thank you.

**Comment by ssarfraz** [comment]
hi this is provided in the Matlab implementation https://github.com/ssarfraz/FINCH-Clustering/blob/06e66358bcc4b18cc70afc745f692610b23bf557/TW-FINCH/matlab/util_fns/read_video.m#L44

For python you can do something similar. There is no further support planned on this repo. so closing the issue. Thanks

**Comment by pulkitkumar95** [comment]
I am getting a lower F1 score using the python code too for all the datasets. And significantly lower too.  My intuition is that since F1 is harmonic mean, it should not be averaged across all the video predictions. So possible that there is a bug in this line 
https://github.com/ssarfraz/FINCH-Clustering/blob/06e66358bcc4b18cc70afc745f692610b23bf557/TW-FINCH/run_on_dataset.py#L97

My matlab knowledge is limited, @ssarfraz could you please comment on this and let us know if in matlab it is handled differently?

Thank you.

**Comment by ssarfraz** [comment]
@pulkitkumar95 what do u mean on all the datasets? The paper only reports f1 for youtube with 75% bg dropped.  The python eval doesn't have 75% bg removed on YTI so you may want to implement it yourself.

Also I don't see much discrepancy on the python results when i run it on Breakfast as you have mentioned here https://github.com/ssarfraz/FINCH-Clustering/issues/27#issue-1584747611  . See below the screen shot of my run

![Screenshot from 2023-02-20 17-20-43](https://user-images.githubusercontent.com/15046958/220160821-2abada04-c585-473d-b859-4417c8e1ba41.png)

**Comment by April-lyl** [comment]
For YTI, when I repliacted the method in python. I add the code 
![image](https://user-images.githubusercontent.com/56187413/220866795-2c2ac8ca-e09f-4dad-900e-ba3800c44f40.png)

But I can't get the same f1 scores as matlab. The result by python is 
![image](https://user-images.githubusercontent.com/56187413/220867085-e5888609-0948-4cf1-83fd-dcec8fd646a7.png)

**Comment by April-lyl** [comment]
As for 50Salads_eval， I replicated the code in python. But I also can't get the same scores as the matlab.
If the reason is python operates different from matlab?
