### ISSUE TITLE
array is empty with s1 dataset

### ISSUE THREAD

**Issue by egy1st** [ssarfraz/FINCH-Clustering#8]
why the algorithm triger an error when working on s1 dataset from http://cs.joensuu.fi/sipu/datasets/

~/finchcls.py in update_adj(self, adj, d)
     94         v = np.argsort(d[idx])
     95         v = v[:2]
---> 96         x = [idx[0][v[0]], idx[0][v[1]]]
     97         y = [idx[1][v[0]], idx[1][v[1]]]
     98         a = sp.lil_matrix(adj.get_shape())

IndexError: index 0 is out of bounds for axis 0 with size 0

the same error with a1 dataset and "unbalance" dataset

any other datasets it works fine

**Comment by ssarfraz** [comment]
@egy1st , thanks for letting me know. this ones was a little unexpected, actually this toy data has large numbers and their euclidean distance comes out to be larger than 10000 (a value I used in the clust_rank def, to set diagonal elements in the distance mat to a large number so i can just do argmin (instead of sort- more expensive) for getting the 1st nbr). Have fixed this and also added some other support. see the updated read me. run it now it should be fine.

**Comment by egy1st** [comment]
Many Thanks. It works fine now.

Thanks again

Mohamed Abbas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
